//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gitter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gitter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open repository.
        /// </summary>
        internal static string ErrFailedToOpenRepository {
            get {
                return ResourceManager.GetString("ErrFailedToOpenRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path.
        /// </summary>
        internal static string ErrInvalidPath {
            get {
                return ResourceManager.GetString("ErrInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path cannot be empty.
        /// </summary>
        internal static string ErrPathCannotBeEmpty {
            get {
                return ResourceManager.GetString("ErrPathCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid repository..
        /// </summary>
        internal static string ErrPathIsNotValidRepository {
            get {
                return ResourceManager.GetString("ErrPathIsNotValidRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified path is not a valid repository.
        /// </summary>
        internal static string ErrSpecifiedPathIsNotValidRepository {
            get {
                return ResourceManager.GetString("ErrSpecifiedPathIsNotValidRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgRepoAddMedium {
            get {
                object obj = ResourceManager.GetObject("ImgRepoAddMedium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgRepoCloneMedium {
            get {
                object obj = ResourceManager.GetObject("ImgRepoCloneMedium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgRepoInitMedium {
            get {
                object obj = ResourceManager.GetObject("ImgRepoInitMedium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgRepoScanMedium {
            get {
                object obj = ResourceManager.GetObject("ImgRepoScanMedium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgRepositories {
            get {
                object obj = ResourceManager.GetObject("ImgRepositories", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgRepository {
            get {
                object obj = ResourceManager.GetObject("ImgRepository", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgRepositoryAdd {
            get {
                object obj = ResourceManager.GetObject("ImgRepositoryAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgRepositoryExplorer {
            get {
                object obj = ResourceManager.GetObject("ImgRepositoryExplorer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgRepositoryLarge {
            get {
                object obj = ResourceManager.GetObject("ImgRepositoryLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgRepositoryOpen {
            get {
                object obj = ResourceManager.GetObject("ImgRepositoryOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgRepositoryRemove {
            get {
                object obj = ResourceManager.GetObject("ImgRepositoryRemove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgStartPage {
            get {
                object obj = ResourceManager.GetObject("ImgStartPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgStartPageLogo {
            get {
                object obj = ResourceManager.GetObject("ImgStartPageLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgStartPageLogoDark {
            get {
                object obj = ResourceManager.GetObject("ImgStartPageLogoDark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgStartPageLogoGradient {
            get {
                object obj = ResourceManager.GetObject("ImgStartPageLogoGradient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgStartPageLogoGradientDark {
            get {
                object obj = ResourceManager.GetObject("ImgStartPageLogoGradientDark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string StrAbout {
            get {
                return ResourceManager.GetString("StrAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string StrAdd {
            get {
                return ResourceManager.GetString("StrAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Repository.
        /// </summary>
        internal static string StrAddRepository {
            get {
                return ResourceManager.GetString("StrAddRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Service.
        /// </summary>
        internal static string StrAddService {
            get {
                return ResourceManager.GetString("StrAddService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string StrDate {
            get {
                return ResourceManager.GetString("StrDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string StrDescription {
            get {
                return ResourceManager.GetString("StrDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string StrEmail {
            get {
                return ResourceManager.GetString("StrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string StrExit {
            get {
                return ResourceManager.GetString("StrExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string StrHelp {
            get {
                return ResourceManager.GetString("StrHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no available.
        /// </summary>
        internal static string StrlNoAvailable {
            get {
                return ResourceManager.GetString("StrlNoAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string StrlNone {
            get {
                return ResourceManager.GetString("StrlNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Repository.
        /// </summary>
        internal static string StrLoadingRepository {
            get {
                return ResourceManager.GetString("StrLoadingRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string StrName {
            get {
                return ResourceManager.GetString("StrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string StrOpen {
            get {
                return ResourceManager.GetString("StrOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Command Line.
        /// </summary>
        internal static string StrOpenCommandLine {
            get {
                return ResourceManager.GetString("StrOpenCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Windows Explorer.
        /// </summary>
        internal static string StrOpenInWindowsExplorer {
            get {
                return ResourceManager.GetString("StrOpenInWindowsExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string StrOptions {
            get {
                return ResourceManager.GetString("StrOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string StrPath {
            get {
                return ResourceManager.GetString("StrPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        internal static string StrProvider {
            get {
                return ResourceManager.GetString("StrProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        internal static string StrRecent {
            get {
                return ResourceManager.GetString("StrRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From List.
        /// </summary>
        internal static string StrRemoveRepository {
            get {
                return ResourceManager.GetString("StrRemoveRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositories.
        /// </summary>
        internal static string StrRepositories {
            get {
                return ResourceManager.GetString("StrRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        internal static string StrRepository {
            get {
                return ResourceManager.GetString("StrRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository Explorer.
        /// </summary>
        internal static string StrRepositoryExplorer {
            get {
                return ResourceManager.GetString("StrRepositoryExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check failed.
        /// </summary>
        internal static string StrsCheckFailed {
            get {
                return ResourceManager.GetString("StrsCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates.
        /// </summary>
        internal static string StrsCheckingForUpdates {
            get {
                return ResourceManager.GetString("StrsCheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string StrSize {
            get {
                return ResourceManager.GetString("StrSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Page.
        /// </summary>
        internal static string StrStartPage {
            get {
                return ResourceManager.GetString("StrStartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v{0} is available.
        /// </summary>
        internal static string StrsVersionIsAvailable {
            get {
                return ResourceManager.GetString("StrsVersionIsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version is up to date.
        /// </summary>
        internal static string StrsYourVersionIsUpToDate {
            get {
                return ResourceManager.GetString("StrsYourVersionIsUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbars.
        /// </summary>
        internal static string StrToolbars {
            get {
                return ResourceManager.GetString("StrToolbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string StrTools {
            get {
                return ResourceManager.GetString("StrTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string StrType {
            get {
                return ResourceManager.GetString("StrType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string StrUrl {
            get {
                return ResourceManager.GetString("StrUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCS.
        /// </summary>
        internal static string StrVCS {
            get {
                return ResourceManager.GetString("StrVCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string StrVersion {
            get {
                return ResourceManager.GetString("StrVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string StrView {
            get {
                return ResourceManager.GetString("StrView", resourceCulture);
            }
        }
    }
}
