//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gitter.GitLab.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gitter.GitLab.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key cannot be empty.
        /// </summary>
        internal static string ErrAPIKeyCannotBeEmpty {
            get {
                return ResourceManager.GetString("ErrAPIKeyCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid API key.
        /// </summary>
        internal static string ErrApiKeyIsInvalid {
            get {
                return ResourceManager.GetString("ErrApiKeyIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate service URL.
        /// </summary>
        internal static string ErrDuplicateServiceUri {
            get {
                return ResourceManager.GetString("ErrDuplicateServiceUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid service URL.
        /// </summary>
        internal static string ErrInvalidServiceUri {
            get {
                return ResourceManager.GetString("ErrInvalidServiceUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No API key specified.
        /// </summary>
        internal static string ErrNoAPIKeySpecified {
            get {
                return ResourceManager.GetString("ErrNoAPIKeySpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project name specified.
        /// </summary>
        internal static string ErrNoProjectNameSpecified {
            get {
                return ResourceManager.GetString("ErrNoProjectNameSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No server name specified.
        /// </summary>
        internal static string ErrNoServerNameSpecified {
            get {
                return ResourceManager.GetString("ErrNoServerNameSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service URL specified.
        /// </summary>
        internal static string ErrNoServiceUriSpecified {
            get {
                return ResourceManager.GetString("ErrNoServiceUriSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name cannot be empty.
        /// </summary>
        internal static string ErrProjectNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("ErrProjectNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name cannot be empty.
        /// </summary>
        internal static string ErrServerNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("ErrServerNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service URL cannot be empty.
        /// </summary>
        internal static string ErrServiceUriCannotBeEmpty {
            get {
                return ResourceManager.GetString("ErrServiceUriCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find GitLab at the specified URL.
        /// </summary>
        internal static string ErrServiceUriIsNotGitLab {
            get {
                return ResourceManager.GetString("ErrServiceUriIsNotGitLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified service URL is not valid.
        /// </summary>
        internal static string ErrServiceUriIsNotValid {
            get {
                return ResourceManager.GetString("ErrServiceUriIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified service URL was added already.
        /// </summary>
        internal static string ErrSpecifiedServiceUriAlreadyExists {
            get {
                return ResourceManager.GetString("ErrSpecifiedServiceUriAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to authorize with the specified API key.
        /// </summary>
        internal static string ErrUnableToAuthorize {
            get {
                return ResourceManager.GetString("ErrUnableToAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string StrAdd {
            get {
                return ResourceManager.GetString("StrAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Server.
        /// </summary>
        internal static string StrAddServer {
            get {
                return ResourceManager.GetString("StrAddServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string StrAll {
            get {
                return ResourceManager.GetString("StrAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        internal static string StrAPIKey {
            get {
                return ResourceManager.GetString("StrAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignee.
        /// </summary>
        internal static string StrAssignee {
            get {
                return ResourceManager.GetString("StrAssignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string StrAuthor {
            get {
                return ResourceManager.GetString("StrAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        internal static string StrBranches {
            get {
                return ResourceManager.GetString("StrBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string StrClose {
            get {
                return ResourceManager.GetString("StrClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string StrClosed {
            get {
                return ResourceManager.GetString("StrClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed By.
        /// </summary>
        internal static string StrClosedBy {
            get {
                return ResourceManager.GetString("StrClosedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        internal static string StrCollapseAll {
            get {
                return ResourceManager.GetString("StrCollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string StrCreatedAt {
            get {
                return ResourceManager.GetString("StrCreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string StrDelete {
            get {
                return ResourceManager.GetString("StrDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        internal static string StrErrors {
            get {
                return ResourceManager.GetString("StrErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        internal static string StrExpandAll {
            get {
                return ResourceManager.GetString("StrExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Tests.
        /// </summary>
        internal static string StrFailedTests {
            get {
                return ResourceManager.GetString("StrFailedTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string StrFind {
            get {
                return ResourceManager.GetString("StrFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string StrFinished {
            get {
                return ResourceManager.GetString("StrFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitLab.
        /// </summary>
        internal static string StrGitLab {
            get {
                return ResourceManager.GetString("StrGitLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash.
        /// </summary>
        internal static string StrHash {
            get {
                return ResourceManager.GetString("StrHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string StrId {
            get {
                return ResourceManager.GetString("StrId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        internal static string StrIssues {
            get {
                return ResourceManager.GetString("StrIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        internal static string StrJobs {
            get {
                return ResourceManager.GetString("StrJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to fetch pipeline information.
        /// </summary>
        internal static string StrlFailedToFetchPipelineInformation {
            get {
                return ResourceManager.GetString("StrlFailedToFetchPipelineInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetching pipeline information....
        /// </summary>
        internal static string StrlFetchingPipelineInformation {
            get {
                return ResourceManager.GetString("StrlFetchingPipelineInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no associated pipelines found.
        /// </summary>
        internal static string StrlNoPipelinesFound {
            get {
                return ResourceManager.GetString("StrlNoPipelinesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pipeline.
        /// </summary>
        internal static string StrlPipeline {
            get {
                return ResourceManager.GetString("StrlPipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone.
        /// </summary>
        internal static string StrMilestone {
            get {
                return ResourceManager.GetString("StrMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string StrName {
            get {
                return ResourceManager.GetString("StrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string StrNext {
            get {
                return ResourceManager.GetString("StrNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string StrOpen {
            get {
                return ResourceManager.GetString("StrOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipelines.
        /// </summary>
        internal static string StrPipelines {
            get {
                return ResourceManager.GetString("StrPipelines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string StrPrevious {
            get {
                return ResourceManager.GetString("StrPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string StrProject {
            get {
                return ResourceManager.GetString("StrProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string StrReference {
            get {
                return ResourceManager.GetString("StrReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string StrRefresh {
            get {
                return ResourceManager.GetString("StrRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string StrRemove {
            get {
                return ResourceManager.GetString("StrRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        internal static string StrServers {
            get {
                return ResourceManager.GetString("StrServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service URL.
        /// </summary>
        internal static string StrServiceUri {
            get {
                return ResourceManager.GetString("StrServiceUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch issues.
        /// </summary>
        internal static string StrsFailedToFetchIssues {
            get {
                return ResourceManager.GetString("StrsFailedToFetchIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch pipelines.
        /// </summary>
        internal static string StrsFailedToFetchPipelines {
            get {
                return ResourceManager.GetString("StrsFailedToFetchPipelines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch test report.
        /// </summary>
        internal static string StrsFailedToFetchTestReport {
            get {
                return ResourceManager.GetString("StrsFailedToFetchTestReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped Tests.
        /// </summary>
        internal static string StrSkippedTests {
            get {
                return ResourceManager.GetString("StrSkippedTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No issues to display.
        /// </summary>
        internal static string StrsNoIssuesToDisplay {
            get {
                return ResourceManager.GetString("StrsNoIssuesToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pipelines to display.
        /// </summary>
        internal static string StrsNoPipelinesToDisplay {
            get {
                return ResourceManager.GetString("StrsNoPipelinesToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tests to display.
        /// </summary>
        internal static string StrsNoTestsToDisplay {
            get {
                return ResourceManager.GetString("StrsNoTestsToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string StrStatus {
            get {
                return ResourceManager.GetString("StrStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed Tests.
        /// </summary>
        internal static string StrSuccessTests {
            get {
                return ResourceManager.GetString("StrSuccessTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View commit on GitLab.
        /// </summary>
        internal static string StrsViewCommitOnGitLab {
            get {
                return ResourceManager.GetString("StrsViewCommitOnGitLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string StrTags {
            get {
                return ResourceManager.GetString("StrTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests.
        /// </summary>
        internal static string StrTests {
            get {
                return ResourceManager.GetString("StrTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string StrTitle {
            get {
                return ResourceManager.GetString("StrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        internal static string StrUpdatedAt {
            get {
                return ResourceManager.GetString("StrUpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Test Report.
        /// </summary>
        internal static string StrViewTestReport {
            get {
                return ResourceManager.GetString("StrViewTestReport", resourceCulture);
            }
        }
    }
}
