//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gitter.GitLab.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gitter.GitLab.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key cannot be empty.
        /// </summary>
        internal static string ErrAPIKeyCannotBeEmpty {
            get {
                return ResourceManager.GetString("ErrAPIKeyCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid API key.
        /// </summary>
        internal static string ErrApiKeyIsInvalid {
            get {
                return ResourceManager.GetString("ErrApiKeyIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate service URL.
        /// </summary>
        internal static string ErrDuplicateServiceUri {
            get {
                return ResourceManager.GetString("ErrDuplicateServiceUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid service URL.
        /// </summary>
        internal static string ErrInvalidServiceUri {
            get {
                return ResourceManager.GetString("ErrInvalidServiceUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No API key specified.
        /// </summary>
        internal static string ErrNoAPIKeySpecified {
            get {
                return ResourceManager.GetString("ErrNoAPIKeySpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project name specified.
        /// </summary>
        internal static string ErrNoProjectNameSpecified {
            get {
                return ResourceManager.GetString("ErrNoProjectNameSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No server name specified.
        /// </summary>
        internal static string ErrNoServerNameSpecified {
            get {
                return ResourceManager.GetString("ErrNoServerNameSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service URL specified.
        /// </summary>
        internal static string ErrNoServiceUriSpecified {
            get {
                return ResourceManager.GetString("ErrNoServiceUriSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name cannot be empty.
        /// </summary>
        internal static string ErrProjectNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("ErrProjectNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name cannot be empty.
        /// </summary>
        internal static string ErrServerNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("ErrServerNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service URL cannot be empty.
        /// </summary>
        internal static string ErrServiceUriCannotBeEmpty {
            get {
                return ResourceManager.GetString("ErrServiceUriCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find GitLab at the specified URL.
        /// </summary>
        internal static string ErrServiceUriIsNotGitLab {
            get {
                return ResourceManager.GetString("ErrServiceUriIsNotGitLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified service URL is not valid.
        /// </summary>
        internal static string ErrServiceUriIsNotValid {
            get {
                return ResourceManager.GetString("ErrServiceUriIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified service URL was added already.
        /// </summary>
        internal static string ErrSpecifiedServiceUriAlreadyExists {
            get {
                return ResourceManager.GetString("ErrSpecifiedServiceUriAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to authorize with the specified API key.
        /// </summary>
        internal static string ErrUnableToAuthorize {
            get {
                return ResourceManager.GetString("ErrUnableToAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgGitLab {
            get {
                object obj = ResourceManager.GetObject("ImgGitLab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgGitLab32 {
            get {
                object obj = ResourceManager.GetObject("ImgGitLab32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgStatusCanceled {
            get {
                object obj = ResourceManager.GetObject("ImgStatusCanceled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgStatusCreated {
            get {
                object obj = ResourceManager.GetObject("ImgStatusCreated", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgStatusFailed {
            get {
                object obj = ResourceManager.GetObject("ImgStatusFailed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgStatusManual {
            get {
                object obj = ResourceManager.GetObject("ImgStatusManual", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgStatusPending {
            get {
                object obj = ResourceManager.GetObject("ImgStatusPending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgStatusPreparing {
            get {
                object obj = ResourceManager.GetObject("ImgStatusPreparing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgStatusRunning {
            get {
                object obj = ResourceManager.GetObject("ImgStatusRunning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgStatusScheduled {
            get {
                object obj = ResourceManager.GetObject("ImgStatusScheduled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgStatusSkipped {
            get {
                object obj = ResourceManager.GetObject("ImgStatusSkipped", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgStatusSuccess {
            get {
                object obj = ResourceManager.GetObject("ImgStatusSuccess", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string StrAdd {
            get {
                return ResourceManager.GetString("StrAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Server.
        /// </summary>
        internal static string StrAddServer {
            get {
                return ResourceManager.GetString("StrAddServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        internal static string StrAPIKey {
            get {
                return ResourceManager.GetString("StrAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitLab.
        /// </summary>
        internal static string StrGitLab {
            get {
                return ResourceManager.GetString("StrGitLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to fetch pipeline information.
        /// </summary>
        internal static string StrlFailedToFetchPipelineInformation {
            get {
                return ResourceManager.GetString("StrlFailedToFetchPipelineInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetching pipeline information....
        /// </summary>
        internal static string StrlFetchingPipelineInformation {
            get {
                return ResourceManager.GetString("StrlFetchingPipelineInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no associated pipelines found.
        /// </summary>
        internal static string StrlNoPipelinesFound {
            get {
                return ResourceManager.GetString("StrlNoPipelinesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pipeline.
        /// </summary>
        internal static string StrlPipeline {
            get {
                return ResourceManager.GetString("StrlPipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string StrName {
            get {
                return ResourceManager.GetString("StrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string StrProject {
            get {
                return ResourceManager.GetString("StrProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string StrRemove {
            get {
                return ResourceManager.GetString("StrRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        internal static string StrServers {
            get {
                return ResourceManager.GetString("StrServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service URL.
        /// </summary>
        internal static string StrServiceUri {
            get {
                return ResourceManager.GetString("StrServiceUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View commit on GitLab.
        /// </summary>
        internal static string StrsViewCommitOnGitLab {
            get {
                return ResourceManager.GetString("StrsViewCommitOnGitLab", resourceCulture);
            }
        }
    }
}
