<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>gitter.rebase-editor</AssemblyName>
    <RootNamespace>gitter.Git.RebaseEditor</RootNamespace>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <PostBuildEvent>..\..\..\Properties\postbuild.cmd $(Configuration) $(TargetFramework)</PostBuildEvent>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PolySharp" Version="1.16.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
