//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gitter.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gitter.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute some actions.
        /// </summary>
        internal static string ErrFailedToRunElevatedProcess {
            get {
                return ResourceManager.GetString("ErrFailedToRunElevatedProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some options could not be applied because gitter was uable to start an elevated process..
        /// </summary>
        internal static string ErrSomeOptionsCouldNotBeApplied {
            get {
                return ResourceManager.GetString("ErrSomeOptionsCouldNotBeApplied", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap IcoApplication {
            get {
                object obj = ResourceManager.GetObject("IcoApplication", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IcoApplicationTerminal {
            get {
                object obj = ResourceManager.GetObject("IcoApplicationTerminal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IcoDocument {
            get {
                object obj = ResourceManager.GetObject("IcoDocument", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IcoDocumentAccess {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentAccess", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IcoDocumentBinary {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentBinary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IcoDocumentCode {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentCode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IcoDocumentExcel {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentExcel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IcoDocumentExcelCsv {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentExcelCsv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IcoDocumentFilm {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentFilm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IcoDocumentFlashMovie {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentFlashMovie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IcoDocumentGlobe {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentGlobe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IcoDocumentImage {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IcoDocumentMusic {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentMusic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IcoDocumentOffice {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentOffice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IcoDocumentOutlook {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentOutlook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IcoDocumentPdf {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentPdf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IcoDocumentPhotoshop {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentPhotoshop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IcoDocumentPhp {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentPhp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IcoDocumentPowerpoint {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentPowerpoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IcoDocumentText {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IcoDocumentVisualStudio {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentVisualStudio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IcoDocumentWord {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentWord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IcoDocumentXaml {
            get {
                object obj = ResourceManager.GetObject("IcoDocumentXaml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgAction {
            get {
                object obj = ResourceManager.GetObject("ImgAction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgActionHover {
            get {
                object obj = ResourceManager.GetObject("ImgActionHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgChecked {
            get {
                object obj = ResourceManager.GetObject("ImgChecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgCheckedHover {
            get {
                object obj = ResourceManager.GetObject("ImgCheckedHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgChevronCollapse {
            get {
                object obj = ResourceManager.GetObject("ImgChevronCollapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgChevronCollapseHover {
            get {
                object obj = ResourceManager.GetObject("ImgChevronCollapseHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgChevronExpand {
            get {
                object obj = ResourceManager.GetObject("ImgChevronExpand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgChevronExpandHover {
            get {
                object obj = ResourceManager.GetObject("ImgChevronExpandHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgColumnExtender {
            get {
                object obj = ResourceManager.GetObject("ImgColumnExtender", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgGoBack {
            get {
                object obj = ResourceManager.GetObject("ImgGoBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgGoForward {
            get {
                object obj = ResourceManager.GetObject("ImgGoForward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgIntermediate {
            get {
                object obj = ResourceManager.GetObject("ImgIntermediate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgIntermediateHover {
            get {
                object obj = ResourceManager.GetObject("ImgIntermediateHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgLog {
            get {
                object obj = ResourceManager.GetObject("ImgLog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgLogDebug {
            get {
                object obj = ResourceManager.GetObject("ImgLogDebug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgLogError {
            get {
                object obj = ResourceManager.GetObject("ImgLogError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgLogInfo {
            get {
                object obj = ResourceManager.GetObject("ImgLogInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgLogWarning {
            get {
                object obj = ResourceManager.GetObject("ImgLogWarning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgMaximize {
            get {
                object obj = ResourceManager.GetObject("ImgMaximize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgMenuCheck {
            get {
                object obj = ResourceManager.GetObject("ImgMenuCheck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgMinus {
            get {
                object obj = ResourceManager.GetObject("ImgMinus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgMinusHovered {
            get {
                object obj = ResourceManager.GetObject("ImgMinusHovered", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgNormalize {
            get {
                object obj = ResourceManager.GetObject("ImgNormalize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgPlus {
            get {
                object obj = ResourceManager.GetObject("ImgPlus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgPlusHovered {
            get {
                object obj = ResourceManager.GetObject("ImgPlusHovered", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgTabMenu {
            get {
                object obj = ResourceManager.GetObject("ImgTabMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgTabMenuExtends {
            get {
                object obj = ResourceManager.GetObject("ImgTabMenuExtends", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgTabScrollLeft {
            get {
                object obj = ResourceManager.GetObject("ImgTabScrollLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgTabScrollRight {
            get {
                object obj = ResourceManager.GetObject("ImgTabScrollRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgUnchecked {
            get {
                object obj = ResourceManager.GetObject("ImgUnchecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgUncheckedHover {
            get {
                object obj = ResourceManager.GetObject("ImgUncheckedHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgViewHostClose {
            get {
                object obj = ResourceManager.GetObject("ImgViewHostClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgViewHostMenu {
            get {
                object obj = ResourceManager.GetObject("ImgViewHostMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgViewHostPin {
            get {
                object obj = ResourceManager.GetObject("ImgViewHostPin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgWebBrowser {
            get {
                object obj = ResourceManager.GetObject("ImgWebBrowser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string StrAbort {
            get {
                return ResourceManager.GetString("StrAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:.
        /// </summary>
        internal static string StrAddColon {
            get {
                return ResourceManager.GetString("StrAddColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},.
        /// </summary>
        internal static string StrAddComma {
            get {
                return ResourceManager.GetString("StrAddComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}....
        /// </summary>
        internal static string StrAddEllipsis {
            get {
                return ResourceManager.GetString("StrAddEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}..
        /// </summary>
        internal static string StrAddPeriod {
            get {
                return ResourceManager.GetString("StrAddPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AntiAlias.
        /// </summary>
        internal static string StrAntiAlias {
            get {
                return ResourceManager.GetString("StrAntiAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string StrAppearance {
            get {
                return ResourceManager.GetString("StrAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string StrApply {
            get {
                return ResourceManager.GetString("StrApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string StrBack {
            get {
                return ResourceManager.GetString("StrBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        internal static string StrBehavior {
            get {
                return ResourceManager.GetString("StrBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string StrBold {
            get {
                return ResourceManager.GetString("StrBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string StrCancel {
            get {
                return ResourceManager.GetString("StrCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearType.
        /// </summary>
        internal static string StrClearType {
            get {
                return ResourceManager.GetString("StrClearType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string StrClose {
            get {
                return ResourceManager.GetString("StrClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        internal static string StrColors {
            get {
                return ResourceManager.GetString("StrColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        internal static string StrColumns {
            get {
                return ResourceManager.GetString("StrColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast.
        /// </summary>
        internal static string StrContrast {
            get {
                return ResourceManager.GetString("StrContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        internal static string StrCopyToClipboard {
            get {
                return ResourceManager.GetString("StrCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string StrDate {
            get {
                return ResourceManager.GetString("StrDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Format.
        /// </summary>
        internal static string StrDateFormat {
            get {
                return ResourceManager.GetString("StrDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string StrDefaultFormat {
            get {
                return ResourceManager.GetString("StrDefaultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string StrDown {
            get {
                return ResourceManager.GetString("StrDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string StrError {
            get {
                return ResourceManager.GetString("StrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        internal static string StrExample {
            get {
                return ResourceManager.GetString("StrExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        internal static string StrException {
            get {
                return ResourceManager.GetString("StrException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        internal static string StrFamily {
            get {
                return ResourceManager.GetString("StrFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string StrFont {
            get {
                return ResourceManager.GetString("StrFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts.
        /// </summary>
        internal static string StrFonts {
            get {
                return ResourceManager.GetString("StrFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        internal static string StrForward {
            get {
                return ResourceManager.GetString("StrForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string StrHide {
            get {
                return ResourceManager.GetString("StrHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string StrIgnore {
            get {
                return ResourceManager.GetString("StrIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Font.
        /// </summary>
        internal static string StrInputFont {
            get {
                return ResourceManager.GetString("StrInputFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO 8601.
        /// </summary>
        internal static string StrISO8601 {
            get {
                return ResourceManager.GetString("StrISO8601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string StrItalic {
            get {
                return ResourceManager.GetString("StrItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string StrLog {
            get {
                return ResourceManager.GetString("StrLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string StrMessage {
            get {
                return ResourceManager.GetString("StrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string StrName {
            get {
                return ResourceManager.GetString("StrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string StrNo {
            get {
                return ResourceManager.GetString("StrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string StrOk {
            get {
                return ResourceManager.GetString("StrOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string StrOptions {
            get {
                return ResourceManager.GetString("StrOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string StrRefresh {
            get {
                return ResourceManager.GetString("StrRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative.
        /// </summary>
        internal static string StrRelative {
            get {
                return ResourceManager.GetString("StrRelative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering Options.
        /// </summary>
        internal static string StrRenderingOptions {
            get {
                return ResourceManager.GetString("StrRenderingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering Quality.
        /// </summary>
        internal static string StrRenderingQuality {
            get {
                return ResourceManager.GetString("StrRenderingQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string StrRetry {
            get {
                return ResourceManager.GetString("StrRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFC 2822.
        /// </summary>
        internal static string StrRFC2822 {
            get {
                return ResourceManager.GetString("StrRFC2822", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        internal static string StrSample {
            get {
                return ResourceManager.GetString("StrSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Bugreport.
        /// </summary>
        internal static string StrSendBugreport {
            get {
                return ResourceManager.GetString("StrSendBugreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string StrShow {
            get {
                return ResourceManager.GetString("StrShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string StrSize {
            get {
                return ResourceManager.GetString("StrSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string StrSource {
            get {
                return ResourceManager.GetString("StrSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell Checking.
        /// </summary>
        internal static string StrSpelling {
            get {
                return ResourceManager.GetString("StrSpelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack.
        /// </summary>
        internal static string StrStack {
            get {
                return ResourceManager.GetString("StrStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string StrStop {
            get {
                return ResourceManager.GetString("StrStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikeout.
        /// </summary>
        internal static string StrStrikeout {
            get {
                return ResourceManager.GetString("StrStrikeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string StrStyle {
            get {
                return ResourceManager.GetString("StrStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot;.
        /// </summary>
        internal static string StrSurroundWithDoubleQuotes {
            get {
                return ResourceManager.GetString("StrSurroundWithDoubleQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;.
        /// </summary>
        internal static string StrSurroundWithSingleQuotes {
            get {
                return ResourceManager.GetString("StrSurroundWithSingleQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Default.
        /// </summary>
        internal static string StrSystemDefault {
            get {
                return ResourceManager.GetString("StrSystemDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string StrTimestamp {
            get {
                return ResourceManager.GetString("StrTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string StrType {
            get {
                return ResourceManager.GetString("StrType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Font.
        /// </summary>
        internal static string StrUIFont {
            get {
                return ResourceManager.GetString("StrUIFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        internal static string StrUnderline {
            get {
                return ResourceManager.GetString("StrUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIX Timestamp.
        /// </summary>
        internal static string StrUNIXTimestamp {
            get {
                return ResourceManager.GetString("StrUNIXTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string StrUp {
            get {
                return ResourceManager.GetString("StrUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Viewer Font.
        /// </summary>
        internal static string StrViewerFont {
            get {
                return ResourceManager.GetString("StrViewerFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible Columns.
        /// </summary>
        internal static string StrVisibleColumns {
            get {
                return ResourceManager.GetString("StrVisibleColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Browser.
        /// </summary>
        internal static string StrWebBrowser {
            get {
                return ResourceManager.GetString("StrWebBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string StrYes {
            get {
                return ResourceManager.GetString("StrYes", resourceCulture);
            }
        }
    }
}
