//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gitter.Redmine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gitter.Redmine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap ImgBug {
            get {
                object obj = ResourceManager.GetObject("ImgBug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgCopyToClipboard {
            get {
                object obj = ResourceManager.GetObject("ImgCopyToClipboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgNews {
            get {
                object obj = ResourceManager.GetObject("ImgNews", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgRedmine {
            get {
                object obj = ResourceManager.GetObject("ImgRedmine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgRefresh {
            get {
                object obj = ResourceManager.GetObject("ImgRefresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgSearchClose {
            get {
                object obj = ResourceManager.GetObject("ImgSearchClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgSearchNext {
            get {
                object obj = ResourceManager.GetObject("ImgSearchNext", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgSearchPrevous {
            get {
                object obj = ResourceManager.GetObject("ImgSearchPrevous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgVersion {
            get {
                object obj = ResourceManager.GetObject("ImgVersion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        internal static string StrApiKey {
            get {
                return ResourceManager.GetString("StrApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned To.
        /// </summary>
        internal static string StrAssignedTo {
            get {
                return ResourceManager.GetString("StrAssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string StrAuthor {
            get {
                return ResourceManager.GetString("StrAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string StrCategory {
            get {
                return ResourceManager.GetString("StrCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string StrClose {
            get {
                return ResourceManager.GetString("StrClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        internal static string StrCopyToClipboard {
            get {
                return ResourceManager.GetString("StrCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string StrCreated {
            get {
                return ResourceManager.GetString("StrCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        internal static string StrCreatedOn {
            get {
                return ResourceManager.GetString("StrCreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string StrDescription {
            get {
                return ResourceManager.GetString("StrDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Done.
        /// </summary>
        internal static string StrDoneRation {
            get {
                return ResourceManager.GetString("StrDoneRation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        internal static string StrDueDate {
            get {
                return ResourceManager.GetString("StrDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string StrFind {
            get {
                return ResourceManager.GetString("StrFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string StrId {
            get {
                return ResourceManager.GetString("StrId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string StrIdentifier {
            get {
                return ResourceManager.GetString("StrIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        internal static string StrIssues {
            get {
                return ResourceManager.GetString("StrIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string StrName {
            get {
                return ResourceManager.GetString("StrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string StrNews {
            get {
                return ResourceManager.GetString("StrNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string StrNext {
            get {
                return ResourceManager.GetString("StrNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string StrPrevious {
            get {
                return ResourceManager.GetString("StrPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string StrPriority {
            get {
                return ResourceManager.GetString("StrPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string StrProject {
            get {
                return ResourceManager.GetString("StrProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redmine.
        /// </summary>
        internal static string StrRedmine {
            get {
                return ResourceManager.GetString("StrRedmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.redmine.org.
        /// </summary>
        internal static string StrRedmineUrl {
            get {
                return ResourceManager.GetString("StrRedmineUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string StrRefresh {
            get {
                return ResourceManager.GetString("StrRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service URL.
        /// </summary>
        internal static string StrServiceUri {
            get {
                return ResourceManager.GetString("StrServiceUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to fetch issues.
        /// </summary>
        internal static string StrsFailedToFetchIssues {
            get {
                return ResourceManager.GetString("StrsFailedToFetchIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to fetch news.
        /// </summary>
        internal static string StrsFailedToFetchNews {
            get {
                return ResourceManager.GetString("StrsFailedToFetchNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to fetch versions.
        /// </summary>
        internal static string StrsFailedToFetchVersions {
            get {
                return ResourceManager.GetString("StrsFailedToFetchVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching issues.
        /// </summary>
        internal static string StrsFetchingIssues {
            get {
                return ResourceManager.GetString("StrsFetchingIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching news.
        /// </summary>
        internal static string StrsFetchingNews {
            get {
                return ResourceManager.GetString("StrsFetchingNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching versions.
        /// </summary>
        internal static string StrsFetchingVersions {
            get {
                return ResourceManager.GetString("StrsFetchingVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No issues to display.
        /// </summary>
        internal static string StrsNoIssuesToDisplay {
            get {
                return ResourceManager.GetString("StrsNoIssuesToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No news to display.
        /// </summary>
        internal static string StrsNoNewsToDisplay {
            get {
                return ResourceManager.GetString("StrsNoNewsToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No versions to display.
        /// </summary>
        internal static string StrsNoVersionsToDisplay {
            get {
                return ResourceManager.GetString("StrsNoVersionsToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string StrStartDate {
            get {
                return ResourceManager.GetString("StrStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string StrStatus {
            get {
                return ResourceManager.GetString("StrStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string StrSubject {
            get {
                return ResourceManager.GetString("StrSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string StrSummary {
            get {
                return ResourceManager.GetString("StrSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unassigned.
        /// </summary>
        internal static string StrsUnassigned {
            get {
                return ResourceManager.GetString("StrsUnassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string StrTitle {
            get {
                return ResourceManager.GetString("StrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker.
        /// </summary>
        internal static string StrTracker {
            get {
                return ResourceManager.GetString("StrTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        internal static string StrUpdated {
            get {
                return ResourceManager.GetString("StrUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated On.
        /// </summary>
        internal static string StrUpdatedOn {
            get {
                return ResourceManager.GetString("StrUpdatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string StrVersion {
            get {
                return ResourceManager.GetString("StrVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versions.
        /// </summary>
        internal static string StrVersions {
            get {
                return ResourceManager.GetString("StrVersions", resourceCulture);
            }
        }
    }
}
