//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gitter.Git.AccessLayer.CLI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gitter.Git.AccessLayer.CLI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autodetect.
        /// </summary>
        internal static string StrAutodetect {
            get {
                return ResourceManager.GetString("StrAutodetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string StrBrowse {
            get {
                return ResourceManager.GetString("StrBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Line Interface.
        /// </summary>
        internal static string StrCommandLineInterface {
            get {
                return ResourceManager.GetString("StrCommandLineInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string StrDownload {
            get {
                return ResourceManager.GetString("StrDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating archive from &apos;{0}&apos;.
        /// </summary>
        internal static string StrfCreatingArchiveFrom {
            get {
                return ResourceManager.GetString("StrfCreatingArchiveFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Version.
        /// </summary>
        internal static string StrFoundVersion {
            get {
                return ResourceManager.GetString("StrFoundVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string StrInstall {
            get {
                return ResourceManager.GetString("StrInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Version.
        /// </summary>
        internal static string StrLatestVersion {
            get {
                return ResourceManager.GetString("StrLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restart required.
        /// </summary>
        internal static string StrlRestartRequired {
            get {
                return ResourceManager.GetString("StrlRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unavailable.
        /// </summary>
        internal static string StrlUnavailable {
            get {
                return ResourceManager.GetString("StrlUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to git.exe.
        /// </summary>
        internal static string StrPathToGitExe {
            get {
                return ResourceManager.GetString("StrPathToGitExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSysGit command line interface.
        /// </summary>
        internal static string StrProviderName {
            get {
                return ResourceManager.GetString("StrProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string StrRefresh {
            get {
                return ResourceManager.GetString("StrRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always autodetect.
        /// </summary>
        internal static string StrsAlwaysAutodetect {
            get {
                return ResourceManager.GetString("StrsAlwaysAutodetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning stash.
        /// </summary>
        internal static string StrsCleaningStash {
            get {
                return ResourceManager.GetString("StrsCleaningStash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to remote host.
        /// </summary>
        internal static string StrsConnectingToRemoteHost {
            get {
                return ResourceManager.GetString("StrsConnectingToRemoteHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback to ANSI codepage if UTF-8 fails to decode characters.
        /// </summary>
        internal static string StrsFallbackToAnsi {
            get {
                return ResourceManager.GetString("StrsFallbackToAnsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log command line interface calls.
        /// </summary>
        internal static string StrsLogCLICalls {
            get {
                return ResourceManager.GetString("StrsLogCLICalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for files.
        /// </summary>
        internal static string StrsLookingForFiles {
            get {
                return ResourceManager.GetString("StrsLookingForFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying stashed changes.
        /// </summary>
        internal static string StrsPerformingStashApply {
            get {
                return ResourceManager.GetString("StrsPerformingStashApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing stash drop.
        /// </summary>
        internal static string StrsPerformingStashDrop {
            get {
                return ResourceManager.GetString("StrsPerformingStashDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring stashed changes.
        /// </summary>
        internal static string StrsPerformingStashPop {
            get {
                return ResourceManager.GetString("StrsPerformingStashPop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to searching.
        /// </summary>
        internal static string StrsSearching {
            get {
                return ResourceManager.GetString("StrsSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for stale branches.
        /// </summary>
        internal static string StrsSearchingStaleBranches {
            get {
                return ResourceManager.GetString("StrsSearchingStaleBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify manually.
        /// </summary>
        internal static string StrsSpecifyManually {
            get {
                return ResourceManager.GetString("StrsSpecifyManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string StrsUnknown {
            get {
                return ResourceManager.GetString("StrsUnknown", resourceCulture);
            }
        }
    }
}
