//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gitter.TeamCity.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gitter.TeamCity.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token cannot be empty.
        /// </summary>
        internal static string ErrAPIKeyCannotBeEmpty {
            get {
                return ResourceManager.GetString("ErrAPIKeyCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid access token.
        /// </summary>
        internal static string ErrApiKeyIsInvalid {
            get {
                return ResourceManager.GetString("ErrApiKeyIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate service URL.
        /// </summary>
        internal static string ErrDuplicateServiceUri {
            get {
                return ResourceManager.GetString("ErrDuplicateServiceUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid service URL.
        /// </summary>
        internal static string ErrInvalidServiceUri {
            get {
                return ResourceManager.GetString("ErrInvalidServiceUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No access token specified.
        /// </summary>
        internal static string ErrNoAPIKeySpecified {
            get {
                return ResourceManager.GetString("ErrNoAPIKeySpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project name specified.
        /// </summary>
        internal static string ErrNoProjectNameSpecified {
            get {
                return ResourceManager.GetString("ErrNoProjectNameSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No server name specified.
        /// </summary>
        internal static string ErrNoServerNameSpecified {
            get {
                return ResourceManager.GetString("ErrNoServerNameSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service URL specified.
        /// </summary>
        internal static string ErrNoServiceUriSpecified {
            get {
                return ResourceManager.GetString("ErrNoServiceUriSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No username specified.
        /// </summary>
        internal static string ErrNoUsernameSpecified {
            get {
                return ResourceManager.GetString("ErrNoUsernameSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name cannot be empty.
        /// </summary>
        internal static string ErrProjectNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("ErrProjectNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name cannot be empty.
        /// </summary>
        internal static string ErrServerNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("ErrServerNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service URL cannot be empty.
        /// </summary>
        internal static string ErrServiceUriCannotBeEmpty {
            get {
                return ResourceManager.GetString("ErrServiceUriCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find TeamCity at the specified URL.
        /// </summary>
        internal static string ErrServiceUriIsNotTeamCity {
            get {
                return ResourceManager.GetString("ErrServiceUriIsNotTeamCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified service URL is not valid.
        /// </summary>
        internal static string ErrServiceUriIsNotValid {
            get {
                return ResourceManager.GetString("ErrServiceUriIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified service URL was added already.
        /// </summary>
        internal static string ErrSpecifiedServiceUriAlreadyExists {
            get {
                return ResourceManager.GetString("ErrSpecifiedServiceUriAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to authorize with the specified API key.
        /// </summary>
        internal static string ErrUnableToAuthorize {
            get {
                return ResourceManager.GetString("ErrUnableToAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be empty.
        /// </summary>
        internal static string ErrUsernameCannotBeEmpty {
            get {
                return ResourceManager.GetString("ErrUsernameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string StrAdd {
            get {
                return ResourceManager.GetString("StrAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Server.
        /// </summary>
        internal static string StrAddServer {
            get {
                return ResourceManager.GetString("StrAddServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Token.
        /// </summary>
        internal static string StrApiKey {
            get {
                return ResourceManager.GetString("StrApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Name.
        /// </summary>
        internal static string StrBranchName {
            get {
                return ResourceManager.GetString("StrBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        internal static string StrBuild {
            get {
                return ResourceManager.GetString("StrBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builds.
        /// </summary>
        internal static string StrBuilds {
            get {
                return ResourceManager.GetString("StrBuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildType.
        /// </summary>
        internal static string StrBuildType {
            get {
                return ResourceManager.GetString("StrBuildType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        internal static string StrCopyToClipboard {
            get {
                return ResourceManager.GetString("StrCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string StrId {
            get {
                return ResourceManager.GetString("StrId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string StrName {
            get {
                return ResourceManager.GetString("StrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string StrNumber {
            get {
                return ResourceManager.GetString("StrNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string StrPassword {
            get {
                return ResourceManager.GetString("StrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string StrProject {
            get {
                return ResourceManager.GetString("StrProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string StrRemove {
            get {
                return ResourceManager.GetString("StrRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string StrServer {
            get {
                return ResourceManager.GetString("StrServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        internal static string StrServers {
            get {
                return ResourceManager.GetString("StrServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service URL.
        /// </summary>
        internal static string StrServiceUri {
            get {
                return ResourceManager.GetString("StrServiceUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Access Token.
        /// </summary>
        internal static string StrSetApiKey {
            get {
                return ResourceManager.GetString("StrSetApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage access tokens.
        /// </summary>
        internal static string StrsManageAccessTokens {
            get {
                return ResourceManager.GetString("StrsManageAccessTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string StrStartDate {
            get {
                return ResourceManager.GetString("StrStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string StrStatus {
            get {
                return ResourceManager.GetString("StrStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamCity.
        /// </summary>
        internal static string StrTeamCity {
            get {
                return ResourceManager.GetString("StrTeamCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string StrUsername {
            get {
                return ResourceManager.GetString("StrUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web URL.
        /// </summary>
        internal static string StrWebUrl {
            get {
                return ResourceManager.GetString("StrWebUrl", resourceCulture);
            }
        }
    }
}
